Feature/node generator template
Intility/templates pull request #75
Opened 2021-11-03 09:42 UTC by MiniMarker

Ferdig med den store overføringsjobben + skrevet om docs til å handle mer om templaten og minde om den faktiske implementasjonen av prosjektet.

2021-11-17 11:51 UTC, JonasKs reviewed
### Feedback on files not commited in this PR:
File: `express/API/Swagger`
> ~But w~Writing an OpenAPI documentation is a tedious task

File: `express/API/Swagger`  
I will only comment this once, but this is true for multiple places:
![bilde](https://user-images.githubusercontent.com/5310116/142192651-faecfa3f-7faf-4118-824e-bdf082db66ee.png)
could be an info block:
![bilde](https://user-images.githubusercontent.com/5310116/142192723-d4789be5-433d-4169-9aeb-a748f8e4b79c.png)


File: `express/API/Swagger`  
> ~But t~This might break the default redirection logic provided by us.

File: `express/API/Azure/Event-Grid`   
Entire file is outdated and should be rewritten/deleted.


#### Other feedback 
I've created my app, but I'm not really in a position to run it. I think it should be crystal clear on how to run the application, where to browse it etc. Herman made me write [this](https://create.intility.app/fastapi/setup/poetry) section, and I wish there was something similar in this documentation, on start commands, docker run commands etc. (I'd love a terminal alternative too, as I'm not using VSCode)

There is a section about TypeScript, but it feels optional? The introduction says `Express TypeScript`. Shouldn't these steps be included by default?

And as a general feedback I think you should consider structuring the docs a bit differently. Suggestion:
- Introduction
- Creating very necessary parts, such as Azure AD stuff
- How to run docker and how to run the webserver
- TypeScript specifics
- How to implement other things, such as Metro, security etc.

2021-11-17 11:51 UTC, JonasKs commented on docusaurus/express/API/express.mdx
>  You can find the easy to follow getting started guide at Express' homepage: ["Express Hello World"](https://expressjs.com/en/starter/hello-world.html). But in larger enterprise applications a more st
Repeating text.

> something, but **larger enterprise applications require a more robust structural layered design.**

> You can find the easy to follow getting started guide at Express' homepage: "Express Hello World". **But in larger enterprise applications a more structured system is needed.**

2021-11-17 11:51 UTC, JonasKs commented on docusaurus/express/API/Security/CORS.mdx
>  Cross-origin resource sharing (CORS) is a mechanism that allows restricted resources on a web page to be requested from another domain outside the domain from which the first resource was served.
I'd mention that this policy is enforced by web browsers, but configured by the backend server.

2021-11-17 11:51 UTC, JonasKs commented on docusaurus/express/API/Security/Authorization.mdx
> +:::
I'd rewrite this to be a short little notice, something like this: 


> This section assume that you have created an [Azure AD application registration](<link to the docs you're linking to>).

2021-11-17 15:09 UTC, h3rmanj requested changes
Good job! Added some comments/nitpicks here and there.

The directory should be renamed from `generator-node` to `express`, to match the general repository structure and naming.

In the docs, I'd like Node.js, TypeScript and application wording of the template to be replaced with Express and API.

As Jonas mentioned the docs should have it's structure revised.
After the Introduction/Installation/Getting Started page, there should be a section with steps that are immediately needed to get the project up and running.
I recommend trying the structure .NET and FastAPI has, with Set Up, Topics and Advanced.

The TypeScript section feels a little out of place as well, we should maybe consider moving that to Intility/Documentation.

2021-11-19 10:14 UTC, h3rmanj commented on .github/workflows/publish-nodejs.yml
> +      - main
This should use tags, with wildcard for express;

```yml
on:
  push:
    tags:
      - 'express-v*'
```

2022-01-14 10:24 UTC, MiniMarker commented
@h3rmanj 
> The directory should be renamed from `generator-node` to `express`, to match the general repository structure and naming.

This is not possible due to yeoman's naming conventions, i can rename the generator to `generator-express` if thats better

2022-01-14 10:27 UTC, h3rmanj commented
> @h3rmanj 
> 
> > The directory should be renamed from `generator-node` to `express`, to match the general repository structure and naming.
> 
> 
> 
> This is not possible due to yeoman's naming conventions, i can rename the generator to `generator-express` if thats better
> 
> 
> 
> 

But the package is not published from the root? And the name will still be `generator-express` as long as it's the package name.

2022-01-14 14:54 UTC, MiniMarker commented on package-lock.json
> +{
It is needed in the ci file to build the yeoman generator

2022-01-14 15:50 UTC, h3rmanj commented on package-lock.json
> +{
The root one? Are you sure?

2022-01-14 16:54 UTC, MiniMarker commented on package-lock.json
> +{
Yes. Yeoman needs the package `yeoman-generator` installed and the pipeline runs `npm ci`

2022-01-14 16:56 UTC, MiniMarker commented on generator-node/generators/app/index.js
> +    this.spawnCommandSync("git", ["checkout", "-b", "qa"]);
I can change to `dev` instead but I think it's better to initialize the project in a dev branch

2022-01-14 16:57 UTC, MiniMarker commented on generator-node/generators/app/index.js
> +        message: `🚀 Insert your Git SSH Address ${chalk.gray("(Optional)")}:`,
Makes sense

2022-01-14 18:40 UTC, MiniMarker commented on generator-node/package.json
> +  "repository": "Intility/templates/generator-node",
Will fix.
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository

2022-01-14 18:41 UTC, MiniMarker commented on generator-node/package.json
> +  "name": "@intility/generator-node",
Yo supports scoped pacakges. Will
Make sure all places match

2022-01-14 18:41 UTC, MiniMarker commented on generator-node/generators/app/index.js
> +        default: this.appname
Will see if this is possible ☺️

2022-01-15 15:17 UTC, MiniMarker commented on generator-node/README.md
> +yo @intility/node                          # Use Yeoman CLI to run the template generator
Updated all install scripts in the project

2022-01-15 15:17 UTC, MiniMarker commented on generator-node/generators/app/templates/README.md
> +```
Will update

2022-02-04 06:47 UTC, MiniMarker commented on generator-node/generators/app/index.js
> +        default: this.appname
I can't seem to make this work.

Can fix this in an later update?

2022-02-04 06:47 UTC, MiniMarker commented on generator-node/generators/app/index.js
> +    this.spawnCommandSync("git", ["checkout", "-b", "qa"]);
Any thoughts?

2022-02-04 07:35 UTC, h3rmanj commented on generator-node/generators/app/index.js
> +        default: this.appname
Of course 😃

2022-02-04 07:37 UTC, h3rmanj commented on generator-node/generators/app/index.js
> +    this.spawnCommandSync("git", ["checkout", "-b", "qa"]);
I'd prefer it to just initialize the git repository, and let it be up to the developer how they want to take it from there. However if you feel like it's needed and as long as it's documented well enough, `dev` is miles better than `qa`.

2022-02-04 10:16 UTC, MiniMarker commented on generator-node/generators/app/index.js
> +    this.spawnCommandSync("git", ["checkout", "-b", "qa"]);
Ait, will remove this

2022-02-05 17:17 UTC, MiniMarker commented on generator-node/generators/app/templates/README.md
> +```
fixed

2022-02-05 17:17 UTC, MiniMarker commented on generator-node/generators/app/index.js
> +    this.spawnCommandSync("git", ["checkout", "-b", "qa"]);
fixed

2022-02-05 17:31 UTC, MiniMarker commented
I think that was all of your comments fixed

2022-02-09 20:01 UTC, MiniMarker commented
Da merger jeg da?

2022-02-09 20:13 UTC, merged